### ISSUE TITLE
consistency between definitions and modules

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#100]
https://github.com/agda/agda-categories/blob/afe50323d35e8eaf664ba8c38e781dbd6f941cb6/Categories/Enriched/Functor.agda#L112

I feel the name of this definition should really be `underlyingFunctor`, so that the dot operator can appear as if it is some sort of the accessor of the definition directly, which improves consistency. what do you think?

**Comment by JacquesCarette** [comment]
I'm fine with that - @sstucki ?

**Comment by sstucki** [comment]
I'm fine with that too, as long as it is consistently enforced accross all the enriched modules. In particular, the corresponding modules for enriched categories and natural transformations should be renamed too. 

For context: in other projects, I use the convention that all public module names start with an uppercase letter, while instances of records start with a lowercase letter. This is clearly not the convention here. Is there a convention?

**Comment by sstucki** [comment]
Actually, I changed my mind.

The idea of this module (and the corresponding ones for enriched categories and natural transformations) is to look a bit like a record module, so one can do things like `open UnderlyingFunctor F` and then use the imported projections/fields as if `F` was an ordinary functor. [Here is an example](https://github.com/agda/agda-categories/blob/master/Categories/Category/Construction/EnrichedFunctors.agda#L67-L89).

Since record modules are typically upper-case, I'd like to keep the module name as is. What about changing the name of `underlying{,Functor,NR}` to `Underlying{,Functor,NT}` instead?

**Comment by JacquesCarette** [comment]
If it is meant to be like a record module, then upper-case makes sense.  If it is more like an accessor, then lower-case.

The previous paragraph was meant to be a proto-naming-convention. In this case, it looks like it would imply that things stay as is.

**Comment by HuStmpHrrr** [comment]
it's probably better to make it upper case, provided that we usually name our special functors with leading upper case.

**Comment by sstucki** [comment]
> it's probably better to make it upper case, provided that we usually name our special functors with leading upper case.

Fixed in #112.
