### ISSUE TITLE
copatterns or records?

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#17]
@andreasabel said (at https://github.com/agda/agda-categories/commit/2d819333763287855a83fba883cc09accea483b5#r34263025) :
> For the new categories library, did you consider using copattern matching instead of records? What is the policy for chosing one over the other?

> Definition by copattern is more lazy, which might have a positive effect on the performance of Agda type-checking. Did you make some experiments?

I personally have not yet used copatterns in any code, so to use them right from the start of this library would have been a big jump. But I have been wanting to experiment with that in some of my code for Pi (the reversible programming language) and RigCategories, where this lazyness might be quite beneficial.

Having said that, as a user of the library, I definitely count on a lot of beta-reduction to happen (at least under C-u C-u C-c C-. ) to 'specialize' from general categorical stuff to the situation I am working in.  Even in the categorical context, getting things like Categories/Functor/Instance/Discrete.agda to work. So really understanding exactly the lazyness of copatterns is very important.

As to the deepest question: is there a settled policy on record/copattern? I would say that there is not. I happen to like records - they match my mental picture of how this information should be captured. But I am definitely willing to be convinced. [Can't speak for @HuStmpHrrr ]

For example, the type-checking time of Categories/Category/Monoidal.agda and Categories/Category/Monoidal/Properties.agda is a bit sluggish. If judicious use of definitions by copatterns would help with that, that would be quite a valuable piece of information.

**Comment by HuStmpHrrr** [comment]
I don't have a preference. I think there are two reasons to use records:

1. the stdlib mainly uses records;
2. Emacs `C-c C-r` works quite well for record directly.

but neither is that important. we can try both if copatterns have advantages. but due to https://github.com/agda/agda/commit/ace8e0d099402a625ac460862ae0a81fcec538d4, will performance still be a part of consideration?

**Comment by andreasabel** [comment]
Maybe I alerted you to this question without need, since I was not aware of https://github.com/agda/agda/commit/ace8e0d099402a625ac460862ae0a81fcec538d4 .  If the rhs of a function clause is a _record_ expression (using actual record syntax), then this clause is internally translated to copattern matching.  
I think this heuristics was introduced to bring out the benefits of copatterns without forcing users to rewrite large code bases.  Thus, you should be fine if you use record syntax.

Orthogonal to this is of course the stylistic policy of the library.

**Comment by JacquesCarette** [comment]
This subtlety is good to know -- especially the part where this doesn't happen when using a record constructor. I tend to like record constructors... but I guess going through a function-as-constructor works.

**Comment by JacquesCarette** [comment]
Right, part of this issue is indeed moot.

Stylistically, I strongly prefer records as the principal way of defining things (i.e. the explicit 'field' keyword and the way things look for record definitions). 

For instantiating records, I have not settled on a style. I would not be against using a mixed style in agda-categories.

I consider this to be a sufficient policy 'decision' for now, and so this issue can be closed.
