### ISSUE TITLE
Unit/Counit Adjunction vs Hom-set Adjunction

### ISSUE THREAD

**Issue by svenkeidel** [agda/agda-categories#188]
I'm trying to write some documentation for adjunctions (#134).

Why do you define adjunctions with a unit `η: id ⇒ GF` and counit `ε: FG ⇒ id` instead of with a natural isomorphism between the hom-sets `hom(FA, B) ≃ hom(A, GB)`? These two definitions are of course equivalent, however, a hom-set adjunction may sometimes be easier to prove and work with.

Is there even a hom-set adjunction in the library? I could not find any.

**Comment by JacquesCarette** [comment]
Hopefully the answer to that is given in a readable way in https://arxiv.org/abs/2005.07059.

Short answer: universe levels. The one definition is fully universe polymorphic, which the other requires that a number of universes be the same. Or weird universe liftings.

The hom-sets version is in Adjoint/Properties, I believe. It's definitely there.

In classical category theory, careful texts talk about small / locally small categories (and never talk about equality being anything other than a point), roughly assuming that all 3 levels are 0. Then the two definitions are indeed fully equivalent. But the definition here covers "all" sizes in one fell swoop.

**Comment by HuStmpHrrr** [comment]
it's actually here https://github.com/agda/agda-categories/blob/master/src/Categories/Adjoint/Equivalents.agda

so yes, we do have the notion using Hom-sets but look how hairy it is. 

Jacques' reply has the point: essentially set theory based category theory only has two levels: 0 means small and 1 is already too large. but if we switch the foundation to type theory, we have a much richer language to cope with.

**Comment by svenkeidel** [comment]
Thanks for the quick answers.

> Hopefully the answer to that is given in a readable way in https://arxiv.org/abs/2005.07059.

Yes, this paper definitely looks helpful, not only for answering this question. I will read it.

> Short answer: universe levels. The one definition is fully universe polymorphic, which the other requires that a number of universes be the same. Or weird universe liftings.

Ok, so basically mapping a unit/counit adjunction to a hom-set adjunction requires the universe levels of `C` and `D` to be the same. Why is that?

Going the other direction, i.e., mapping a hom-set adjunction to a unit-counit adjunction requires to lift the universe levels.
But why is this a problem? Do the proofs get more complicated or is there some other problem?

To me the hom-set definition and the unit/counit definition are just two sides of the same coin. Sometimes it is more convinient to use one definition, sometimes it is more convenient to use the other. Users should be able to pick whatever works best for their use case.

**Comment by sstucki** [comment]
> Ok, so basically mapping a unit/counit adjunction to a hom-set adjunction requires the universe levels of `C` and `D` to be the same. Why is that?

@JacquesCarette and @HuStmpHrrr's answers already give hints, but here's a more complete explanation (which I believe is also in the paper). The issue is the the usual, informal and set-theoretic treatment of category theory brushes over some subtleties that are to do with the size of the collections involved. These subtleties break the equivalence between the (usual) hom-set definition and unit/counit definition.

The hom-set definition relies on a bijection `h` between the hom-sets of two distinct categories `C` and `D`, which may live in different universes, say `Set c` and `Set d`. Normally, we would say that both hom-sets live in the same *category* **Set**, which would make `f` an iso in **Set**, but here we have to be more careful: there isn't just one (large) category **Set** of small sets, there is an entire hierarchy of categories `Setoids a b` of *setoids* indexed by the universe levels `a` and `b` of the underlying sets and equivalence relations. This means that the iso in question has to live in a universe large enough to contain both `Set c` and `Set d`. Because our hierarchy of **Setoids** categories supports only a single universe parameter for it's objects, we need to lift the hom-sets of `C` and `D` into the LUB of the corresponding universes.

And here we loose information: an isomorphism in `Setoid a b` does not tell you anything about the levels of `C` and `D`. And even if you keep that information around, you cannot use `h` to recover the unit/count definition of the adjuction because `h` is not a map between the hom-sets of `C` and `D`, it is a map between their lifted counterparts in some common universe that is neither `Set c` nor `Set d` but their LUB. And you cannot "lower" an element from that LUB (such as `h id`) back into `Set c` or `Set d`. Hence the equivalence between the two definitions is lost.

There's a possible workaround though: one could define an adjuction as an *invertible setoid map* between the (non-lifted) hom-sets of `C` and `D` rather than an iso in some instance of `Setoid`. Morally, the two are of course equivalent, but practically the former can be defined between setoids with *distinct* universe levels, whereas the latter must be defined between setoids with common levels (dictated by the `Setoids` instance it lives in). The "invertible hom-setoids map" definition should then be equivalent to the unit/counit definition, and probably just as useful as the usual hom-set definition (which is just a special case).

BTW, this is a recurring issue in this library. It comes up every time one attempts to characterize a map (morphism, functor, enriched functor, etc.) as being a morphism of some category. I don't think there's a nice solution for this, other than giving a separate, more explicit but universe-polymorphic definition first, and then showing that we obtain the usual, more succinct definition as a special case when the levels coincide. The proof that `Cats` is a CCC is a prime example of this. It only holds if all the levels coincide.

**Comment by JacquesCarette** [comment]
Thanks @sstucki , well said. Summary: in type theory with universe levels, one can talk about 'size' explicitly (instead of being forced to make smallness assumptions), and so we can discover that some definitions are size-polymorphic while others are not. That is one thing that agda-categories witnesses as a side-effect.

**Comment by svenkeidel** [comment]
Wow, these are great explanations! I learned something new, thanks. Yes, I usually don't think about universe levels and size issues when I do category theory with pen and paper. But I guess you have to spell them out precisely when you want to convince a proof assistant.

I will try to compile these explanations into some documentation and link back to this issue. I'll leave this issue open in case I have some more questions.

**Comment by HuStmpHrrr** [comment]
to explain the Yoneda part: what I wanted to say was that it is the set up of type theory that makes category theory less convenient in a proof assistant than with a pen and paper. Yoneda lemma is just another example because it gives you access to reason some random category using some set theoretical language, but as explained above, universe levels usually kick in and turn that language a bit more difficult to use. one interesting question to ask is what do we need from the type theory in order to make category theory a bit more intuitive.

**Comment by JacquesCarette** [comment]
So @svenkeidel is it worth leaving this issue open, or are you now done, and this can be closed?

**Comment by svenkeidel** [comment]
Yeah, sorry. I wasn't able to spend time on this. Feel free to close it.
