### ISSUE TITLE
Where to organize the 'with K' part of the categories library?

### ISSUE THREAD

**Issue by JacquesCarette** [agda/agda-categories#58]
As discussion on various issues make clear (#44 being just the latest), it would be quite useful to have parts of the library, especially that part which makes strong use of `≡` such as `StrictCats, also be able to use the K axiom.  But the whole library is currently built using `--without-K` (on purpose).

So this leads to a non-trivial organization question. For example, should there be a `WithK` hierarchy right below `Categories` (or even parallel to it?) for that? Or should they be intertwined, the way it is for stdlib? I see pros and cons to both, and am undecided which I prefer.

**Comment by sstucki** [comment]
Interesting question.

I don't like the idea of mixing with/without K. (I wonder why it is done like this in the stdlib.)

Having a separate top-level `WithK` module seems like a nice approach. I'd suggest that modules nested in `WithK` should be allowed to refer to those outside, but not vice-versa, so that without-K-modules are not accidentally tainted. And everything that can, should of course still go in the without-K-part of the hierarchy. One could then have a `WithK` version of some modules that re-export functionality from outside (e.g. the weak Grothendieck construction) and add extra proofs/constructions (e.g. the strict Grothendieck construction).

**Comment by JacquesCarette** [comment]
If we go with top-level `WithK`, I completely agree that it ought to be able to refer to anything outside, but not the other way around. And indeed, re-exports are possible.

This might not fully solve the "what is Strict" issue, but at least it'll be clear that everything under the `WithK` hierarchy are strongly truncated.

**Comment by sstucki** [comment]
OK, I'll take care of this when I get some time (and after reworking #42).

**Comment by HuStmpHrrr** [comment]
if `WithK` is a separate hierarchy, wouldn't it be mostly empty?

**Comment by JacquesCarette** [comment]
The sparser the better!  But I'm fine with that.

**Comment by gallais** [comment]
> I don't like the idea of mixing with/without K. (I wonder why it is done like this in the stdlib.)

In the stdlib we adopted `--without-K` and `--safe` as defaults. As a consequence
`--with-K` and "unsafe" are considered outliers and even sometimes evidence of the
compiler not being advanced enough to recognize K-freeness or safety.
Correspondingly modules tainted by these options are left behind, like an afterthought.

**Comment by JacquesCarette** [comment]
Right now, there is no use of `--with-K` at all in the library. So there doesn't seem to be anything to 'do' for this particular issue (other than to decide how to organize things).  And that decision seems to have been done: Use `Categories/WithK` as a hierarchy.
