### ISSUE TITLE
consider adding `id o id = id` in the definition of Category

### ISSUE THREAD

**Issue by HuStmpHrrr** [agda/agda-categories#86]
reading https://arxiv.org/pdf/1401.7694.pdf, section `Which Side Does the Identity Go On?`, it states that picking either left identity or right identity is a "wrong" choice to make constructs definitionally equal. indeed, it is the case, as I realized that the constant functor `const X` is not the same as its opposite, which I wish is the case. Adding this definition might get things going through more smoothly.

**Comment by JacquesCarette** [comment]
Very interesting observation.  Yes, there are frequently 'choices' of using left or right identity when there shouldn't be.  There is also a higher-category coherence that eventually pops up to rectify that (i.e. that left-identity applied to `id o id` must be the same as right-identity applied to `id o id`; it shows up at least somewhere in Rig Category, but likely before that).

But since we're proof-relevant, this means that this will be yet another argument that needs to be provided, no? We should consider supplying constructors that don't burden the user so much when they don't care.

**Comment by HuStmpHrrr** [comment]
yes that's what I did. please check my commit. I am not sure whether `Bicategory` requires similar treatment though. It might be worth putting some thought into this problem.

**Comment by JacquesCarette** [comment]
I've tweaked all the things that I highlighted as sub-optimal.  You are correct that `Bicategory` should have a similar change applied - I'll try to do that later.

Also, I think there's a bunch of places where the left/right choices were made that now could use the 'central' identity. I'll see if I can track those down too.

**Comment by JacquesCarette** [comment]
`Bicategory` is tricky as `op` [can only be defined](https://ncatlab.org/nlab/show/opposite+category#in_enriched_category_theory) for braided monoidal categories.  Of course, the case we're interested in are like that. But making `Bicategory` be definitionally self-dual is probably not worth it. I think a version of `Bicategory` over a braided monoidal category can/should be defined (under a different name) and **it** can be self-dual.

**Comment by HuStmpHrrr** [comment]
yeah, let's not worry about it too much. I just came up with another more closely related thing to worry about.
